simplenodeservice:
    container:
        name: simplenodeservice
    image:
        pullPolicy: IfNotPresent
        repository: index.docker.io/grabnerandi/simplenodeservice
        tag: 1.0.0
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 80
        internalPort: 8080
        name: simplenodeservice
        type: LoadBalancer
